# Generated by Django 4.0.4 on 2022-05-23 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CLIENTE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CLIENTE', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='EQUIPAMENTO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EQUIPAMENTO', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MARCA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MARCA', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='NFE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NFE', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='NFS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NFS', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='STATUS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('STATUS', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TECNICO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TECNICO', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='OS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DATA_ENTRADA', models.DateField(blank=True, null=True)),
                ('DATA_SAIDA', models.DateField(blank=True, null=True)),
                ('DEFEITO_INFORMADO', models.TextField(blank=True, null=True)),
                ('NUMERO_SERIE', models.IntegerField(blank=True, null=True)),
                ('NUMERO_ORÇAMENTO', models.IntegerField(blank=True, null=True)),
                ('DESCRIÇÃO_REPARO', models.TextField(blank=True, null=True)),
                ('NFE', models.IntegerField(blank=True, null=True)),
                ('NFS', models.IntegerField(blank=True, null=True)),
                ('CLIENTE', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='bd_os.cliente')),
                ('EQUIPAMENTO', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='bd_os.equipamento')),
                ('STATUS', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='bd_os.status')),
                ('TECNICO', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='bd_os.tecnico')),
            ],
        ),
        migrations.AddField(
            model_name='equipamento',
            name='MARCA',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='bd_os.marca'),
        ),
    ]
